version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Farouk21
      MYSQL_DATABASE: PruebaTecnica
      MYSQL_USER: Farouk21
      MYSQL_PASSWORD: Farouk21
    networks:
      - mynetwork

  pruebatecnica:
    build: .
    container_name: pruebatecnica
    ports:
      - "2100:2100"
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
