version: "3.9"

services:
  pruebatecnica:
    build: .
    ports:
      - "2100:2100"
    depends_on:
      - mysql
    command: sh -c "sleep 15 && java -jar /app/carlosabdala.jar"
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Farouk21
      MYSQL_DATABASE: PruebaTecnica
      MYSQL_USER: Farouk21
      MYSQL_PASSWORD: Farouk21
    networks:
      - app_network

networks:
  app_network:
    driver: bridge